---
- name: login configs for galera client
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "root"
    group: "root"
    mode: "0600"
  with_items:
    - src: "client.my.cnf.j2"
      dest: "/root/.my.cnf"
#  when: inventory_hostname in groups['galera_all']
  tags:
    - galera-client-user-config


- name: Create the local directories
  file:
    path: "{{ item.path }}"
    state: "directory"
    owner: "{{ item.owner|default('root') }}"
    group: "{{ item.group|default('root') }}"
    mode: "{{ item.mode|default('0755') }}"
    recurse: "{{ item.recurse|default('false') }}"
  with_items:
    - { path: "/var/log/mysql_logs/", owner: "mysql", group: "syslog", mode: "2755" }
  tags:
    - galera-config

- name: mariadb configs
  template:
    src: "{{ item.key }}"
    dest: "{{ item.value.dest }}"
    owner: "{{ item.value.owner|default('root') }}"
    group: "{{ item.value.group|default('root') }}"
    mode: "{{ item.value.mode|default('0644') }}"
  with_dict: "{{ templates }}"
  tags:
    - galera-config

- name: remove default mysql_safe_syslog
  file:
    path: "/etc/mysql/conf.d/mysqld_safe_syslog.cnf"
    state: absent
  tags:
    - galera-config

- name: Remove policy-rc
  file:
    path: "/usr/sbin/policy-rc.d"
    state: absent
  tags:
    - galera-config
