---
- name: Install galera packages
  apt:
    pkg: "{{ item }}"
    state: present
  register: install_packages
  until: install_packages|success
  retries: 5
  delay: 2
  with_items:
    - mariadb-client
    - mariadb-galera-server-10.0
    - galera
    - python-mysqldb
    - rsync
