---
- name: start master mysql
  service: name=mysql state=started args="--wsrep-new-cluster"
  when:
    - inventory_hostname == "{{ groups['galera_all'][0] }}"
  ignore_errors: yes

- name: start slave mysql
  service: name=mysql state=started
  when:
    - inventory_hostname != "{{ groups['galera_all'][0] }}"
  ignore_errors: yes

- name: sleep 30 s
  shell: sleep 30

#解决galera集群协商的问题
- name: restart master mysql
  service: name=mysql state=restarted args="--wsrep-new-cluster"
  when:
    - inventory_hostname == "{{ groups['galera_all'][0] }}"
  ignore_errors: yes


- name: restart slave mysql
  service: name=mysql state=restarted
  when:
    - inventory_hostname != "{{ groups['galera_all'][0] }}"
  ignore_errors: yes

- name: login configs for galera client
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "root"
    group: "root"
    mode: "0600"
  with_items:
    - src: "client.my.cnf.j2"
      dest: "/root/.my.cnf"
  tags:
    - galera-client-user-config
